# Generated by Django 3.1.7 on 2021-04-11 03:05

import api.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.URLField(max_length=256, primary_key=True, serialize=False)),
                ('host', models.URLField(default='', max_length=256)),
                ('url', models.URLField(default='', max_length=256)),
                ('displayName', models.CharField(default='', max_length=55)),
                ('username', models.CharField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('author', models.CharField(default='', max_length=256)),
                ('post', models.CharField(default='', max_length=256)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(default='', max_length=256)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=256)),
                ('items', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.URLField(default='', max_length=256)),
                ('summary', models.CharField(default='', max_length=256)),
                ('author', models.URLField(default='', max_length=256)),
                ('object', models.URLField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256, unique=True)),
                ('auth', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.URLField(max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('source', models.URLField(default='', max_length=256)),
                ('origin', models.URLField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=256)),
                ('contentType', models.CharField(default='', max_length=55)),
                ('content', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], default='PUBLIC', max_length=256)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.URLField(default='', max_length=256)),
                ('categories', models.JSONField(blank=True, default=api.models._list, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('unlisted', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=256)),
                ('to_user', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('R', 'Requested'), ('A', 'Accepted'), ('D', 'Declined')], default='Requested', max_length=1)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
