# Generated by Django 3.1.7 on 2021-03-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210329_1524'),
    ]

    operations = [
    ]
