# Generated by Django 3.1.7 on 2021-04-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210401_1521'),
    ]

    operations = [
    ]
