# Generated by Django 3.1.7 on 2021-04-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210401_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[('WEB', 'web'), ('TUTORIAL', 'tutorial')], default='WEB', max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], default='PUBLIC', max_length=256),
        ),
    ]
