# Generated by Django 3.1.7 on 2021-03-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210329_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
