# Generated by Django 3.1.7 on 2021-03-31 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210329_1542'),
    ]

    operations = [
    ]
