# Generated by Django 3.1.7 on 2021-04-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210401_0124'),
    ]

    operations = [
    ]
