# Generated by Django 3.1.7 on 2021-04-01 07:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210401_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.JSONField(default=api.models.default_list),
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=True),
        ),
    ]
