# Generated by Django 3.1.7 on 2021-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210401_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(default='', max_length=256),
        ),
    ]
