# Generated by Django 3.1.7 on 2021-04-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210401_0246'),
    ]

    operations = [
    ]
