# Generated by Django 3.1.7 on 2021-04-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210401_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='', max_length=55),
        ),
    ]
