# Generated by Django 3.1.7 on 2021-04-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_author_displayname'),
    ]

    operations = [
    ]
